import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import logging

logger = logging.getLogger(__name__)

SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")

def send_alert_email(event, analysis):
    """Synchronous function to send email, to be run as a background task."""
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = f"[Log Alert] {event.k8s_namespace}/{event.k8s_app_label}"

    body = f"""
    <html>
    <body style="
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f4f7f9;
        padding: 20px;
        color: #333333;
        line-height: 1.6;
    ">
        <div style="
            max-width: 600px;
            margin: auto;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
            border-top: 5px solid #d9534f;
        ">
            
            <div style="padding: 20px; border-bottom: 1px solid #eee;">
                <h2 style="margin: 0 0 6px; color: #d9534f; font-size: 20px; line-height: 1.4;">
                    🚨 Log Analysis Report
                </h2>
                <p style="margin: 0; font-size: 14px; color: #666;">
                    Namespace: <b>{event.k8s_namespace}</b> | App: <b>{event.k8s_app_label}</b>
                </p>
            </div>

            <div style="padding: 15px 20px; background-color: #f8fafc; border-bottom: 1px solid #eee;">
                <h3 style="margin: 0 0 10px; font-size: 15px; color: #333; line-height: 1.4;">
                    🧾 Log Message
                </h3>
                <div style="
                    font-family: Consolas, 'Courier New', monospace;
                    font-size: 12px;
                    line-height: 1.5;
                    white-space: pre-wrap;
                    word-break: break-word;
                    max-height: 150px; 
                    overflow-y: auto;
                ">{event.message}</div>
            </div>

            <div style="padding: 20px; background-color: #fff9f9; border-top: 1px solid #eee;">
                <h3 style="margin: 0 0 12px; font-size: 16px; color: #d9534f; line-height: 1.4;">
                    🔍 AI Analysis
                </h3>
                <table style="width: 100%; border-collapse: collapse; line-height: 1.6;">
                    <tr>
                        <td style="padding: 6px 0; font-weight: bold; width: 140px; vertical-align: top;">
                            Service Affected:
                        </td>
                        <td style="padding: 6px 0;">
                            {analysis.get('service_affected')}
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 6px 0; font-weight: bold; vertical-align: top;">
                            Probable Cause:
                        </td>
                        <td style="padding: 6px 0;">
                            {analysis.get('probable_cause')}
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 6px 0; font-weight: bold; vertical-align: top;">
                            Suggested Action:
                        </td>
                        <td style="padding: 6px 0;">
                            {analysis.get('suggested_action')}
                        </td>
                    </tr>
                </table>
            </div>

            <div style="padding: 20px; border-top: 1px solid #eee; font-size: 13px; color: #555;">
                <h3 style="margin: 0 0 10px; font-size: 15px; color: #333; line-height: 1.4;">
                    📦 Infrastructure Context
                </h3>
                <p style="margin: 0 0 4px;"><b>Pod Name:</b> {event.k8s_pod}</p>
                <p style="margin: 0 0 4px;"><b>Container:</b> {event.k8s_container}</p>
                <p style="margin: 0 0 4px;"><b>Image:</b> {event.k8s_image}</p>
                <p style="margin: 0;"><b>Timestamp:</b> {event.timestamp}</p>
            </div>
        </div>
        
        <div style="
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
            color: #999;
            line-height: 1.6;
        ">
            This alert was automatically generated by the LLM Log Analyzer Service<br>
            <strong>Note:</strong> This is an automated message. Please do not reply to this email
        </div>
    </body>
    </html>
    """
    msg.attach(MIMEText(body, 'html'))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()  
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.send_message(msg)
            logger.info(f"📧 Alert email sent to {RECEIVER_EMAIL}")
    except Exception as e:
        logger.error(f"❌ Failed to send email: {e}")